<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

use App\Models\KategoriPsuModel;
use App\Models\JenisPsuModel;
use App\Models\PsuModel;
use App\Models\PsuAttributeModel;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Artisan;

class PsuAttributesSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $dt_psu_attributes = 
        [
        ["1","1","1","1","Panjang Jalan","Meter (m)",""],
        ["2","1","1","1","Lebar Jalan","Meter (m)",""],
        ["3","1","1","1","Kondisi Permukaan","Kualitas aspal/beton", "tingkat kerusakan","Baik,Rusak Sedang,Rusak Parah"],
        ["4","1","1","1","Volume Lalu Lintas","Kendaraan per hari",""],
        ["5","1","1","1","Kecepatan Rata-rata","Meter per jam (meter/jam)",""],
        ["6","1","1","2","Panjang Jalan","Meter (m)",""],
        ["7","1","1","2","Lebar Jalan","Meter (m)",""],
        ["8","1","1","2","Jumlah Lajur", "Unit",""],
        ["9","1","1","2","Kondisi Permukaan","Kualitas aspal/beton", "tingkat kerusakan","Baik,Rusak Sedang,Rusak Parah"],
        ["10","1","1","2","Volume Lalu Lintas", "Kendaraan per hari",""],
        ["11","1","1","2","Kecepatan Rata-rata","Meter per jam (meter/jam)",""],
        ["12","1","1","3","Panjang Jalan","Meter (m)",""],
        ["13","1","1","3","Lebar Jalan","Meter (m)",""],
        ["14","1","1","3","Kondisi Permukaan","Kualitas aspal/beton", "tingkat kerusakan","Baik,Rusak Sedang,Rusak Parah"],
        ["15","1","1","3","Volume Lalu Lintas", "Kendaraan per hari",""],
        ["16","1","2","7","Panjang Saluran","Meter (m)",""],
        ["17","1","2","7","Lebar Saluran","Meter (m)",""],
        ["18","1","2","7","Kedalaman Saluran","Meter (m)",""],
        ["19","1","2","7","Kondisi",    "Tingkat Kebersihan, Keberadaan Sampah","Baik,Rusak Sedang,Rusak Parah"],
        ["20","1","2","8","Panjang Saluran","Meter (m)",""],
        ["21","1","2","8","Diameter Saluran","Milimeter (mm)",""],
        ["22","1","2","8","Kondisi",    "Tingkat Kebersihan, Tingkat Kerusakan","Baik,Rusak Sedang,Rusak Parah"],
        ["23","1","2","9","Luas Kolam","Meter persegi (m<sup>2</sup>)",""],
        ["24","1","2","9","Kedalaman Kolam","Meter (m)",""],
        ["25","1","2","9","Kapasitas Penyimpanan","Meter kubik (m<sup>2</sup>)",""],
        ["26","1","2","9","Kondisi",    "Usia Fasilitas, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["27","1","2","10","Jumlah Pompa", "Unit",""],
        ["28","1","2","10","Kapasitas Pompa", "Liter per detik (L/s)",""],
        ["29","1","2","10","Kondisi",   "Usia Pompa, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["30","1","3","11","Kapasitas Produksi", "Liter per detik (L/s) atau meter kubik per hari (m<sup>2</sup>/hari)",""],
        ["31","1","3","11","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["32","1","3","11","Kondisi",   "Usia Fasilitas, Tingkat Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["33","1","3","13","Panjang Jaringan","Meter (m)",""],
        ["34","1","3","13","Diameter Pipa","Milimeter (mm)",""],
        ["35","1","3","13","Kondisi",   "Usia Jaringan, Tingkat Kebocoran","Baik,Rusak Sedang,Rusak Parah"],
        ["36","1","3","12","Kapasitas Penyimpanan","Meter kubik (m<sup>2</sup>)",""],
        ["37","1","3","12","Kondisi",   "Usia Fasilitas, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["38","1","3","64","Jumlah Hidran", "Unit",""],
        ["39","1","3","64","Kondisi",   "Fungsi Dan Aksesibilitas","Baik,Rusak Sedang,Rusak Parah"],
        ["40","1","4","15","Jumlah Unit", "Unit",""],
        ["41","1","4","15","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["42","1","4","15","Kondisi",   "Kebersihan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["43","1","4","0","Kapasitas Pengolahan","Meter kubik per hari (m<sup>2</sup>/hari)",""],
        ["44","1","4","0","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["45","1","4","0","Kondisi",    "Usia Fasilitas, Tingkat Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["46","1","4","16","Jumlah Unit", "Unit",""],
        ["47","1","4","16","Kapasitas Penyimpanan","Meter kubik (m<sup>2</sup>)",""],
        ["48","1","4","16","Kondisi",   "Usia Fasilitas, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["49","1","4","0","Panjang Jaringan","Meter (m)",""],
        ["50","1","4","0","Diameter Pipa","Milimeter (mm)",""],
        ["51","1","4","0","Kondisi",    "Usia Jaringan, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["52","1","5","18","Kapasitas Pengolahan", "Liter per detik (L/s) atau meter kubik per hari (m<sup>2</sup>/hari)",""],
        ["53","1","5","18","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["54","1","5","18","Kondisi",   "Usia Fasilitas, Tingkat Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["55","1","5","19","Panjang Jaringan","Meter (m)",""],
        ["56","1","5","19","Diameter Pipa","Milimeter (mm)",""],
        ["57","1","5","19","Kondisi",   "Usia Jaringan, Tingkat Kebocoran","Baik,Rusak Sedang,Rusak Parah"],
        ["58","1","5","0","Panjang Saluran","Meter (m)",""],
        ["59","1","5","0","Lebar Saluran","Meter (m)",""],
        ["60","1","5","0","Kondisi",    "Tingkat Kebersihan, Keberadaan Sampah","Baik,Rusak Sedang,Rusak Parah"],
        ["61","1","5","20","Luas Kolam","Meter persegi (m<sup>2</sup>)",""],
        ["62","1","5","20","Kedalaman Kolam","Meter (m)",""],
        ["63","1","5","20","Kapasitas Penyimpanan","Meter kubik (m<sup>2</sup>)",""],
        ["64","1","5","20","Kondisi",   "Usia Fasilitas, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["65","2","6","22","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["66","2","6","22","Jumlah Toko", "Unit",""],
        ["67","2","6","22","Kondisi",   "Usia Bangunan, Tingkat Hunian","Baik,Rusak Sedang,Rusak Parah"],
        ["68","2","6","23","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["69","2","6","23","Jumlah Kios/Pedagang", "Unit",""],
        ["70","2","6","23","Kondisi",   "Kebersihan, Fasilitas Sanitasi","Baik,Rusak Sedang,Rusak Parah"],
        ["71","2","6","24","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["72","2","6","24","Jumlah Cabang", "Unit",""],
        ["73","2","6","24","Kondisi",   "Usia Bangunan, Tingkat Kebersihan","Baik,Rusak Sedang,Rusak Parah"],
        ["74","2","6","25","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["75","2","6","25","Jumlah Toko/Kios", "Unit",""],
        ["76","2","6","25","Kondisi",   "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["77","2","7","26","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["78","2","7","26","Jumlah Pegawai", "Orang",""],
        ["79","2","7","26","Kondisi",   "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["80","2","7","27","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["81","2","7","27","Jumlah Personel", "Orang",""],
        ["82","2","7","27","Kondisi",   "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["83","2","7","28","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["84","2","7","28","Jumlah Layanan", "Jenis layanan",""],
        ["85","2","7","28","Kondisi",   "Usia Bangunan, Efisiensi Layanan","Baik,Rusak Sedang,Rusak Parah"],
        ["86","2","7","29","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["87","2","7","29","Jumlah Layanan", "Jenis layanan",""],
        ["88","2","7","29","Kondisi",   "Usia Bangunan, Efisiensi Layanan","Baik,Rusak Sedang,Rusak Parah"],
        ["89","2","8","30","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["90","2","8","30","Jumlah Kelas", "Unit",""],
        ["91","2","8","30","Kapasitas Siswa", "Orang",""],
        ["92","2","8","30","Kondisi",   "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["93","2","8","31","Luas Kampus", "Hektar (ha)",""],
        ["94","2","8","31","Jumlah Fakultas", "Unit",""],
        ["95","2","8","31","Jumlah Mahasiswa", "Orang",""],
        ["96","2","8","31","Kondisi",   "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["97","2","8","32","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["98","2","8","32","Jumlah Koleksi Buku", "Unit",""],
        ["99","2","8","32","Kondisi",   "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["100","2","8","33","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["101","2","8","33","Jumlah Peralatan", "Unit",""],
        ["102","2","8","33","Kondisi",  "Usia Peralatan, Kecanggihan Teknologi","Baik,Rusak Sedang,Rusak Parah"],
        ["103","2","9","34","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["104","2","9","34","Jumlah Tempat Tidur", "Unit",""],
        ["105","2","9","34","Jumlah Dokter/Perawat", "Orang",""],
        ["106","2","9","34","Kondisi",  "Usia Bangunan, Peralatan Medis","Baik,Rusak Sedang,Rusak Parah"],
        ["107","2","9","35","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["108","2","9","35","Jumlah Ruangan", "Unit",""],
        ["109","2","9","35","Jumlah Tenaga Medis", "Orang",""],
        ["110","2","9","35","Kondisi",  "Usia Bangunan, Peralatan Medis","Baik,Rusak Sedang,Rusak Parah"],
        ["111","2","9","36","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["112","2","9","36","Jumlah Ruangan", "Unit",""],
        ["113","2","9","36","Jumlah Tenaga Medis", "Orang",""],
        ["114","2","9","36","Kondisi",  "Usia Bangunan, Peralatan Medis","Baik,Rusak Sedang,Rusak Parah"],
        ["115","2","9","37","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["116","2","9","37","Jumlah Obat yang Tersedia", "Unit",""],
        ["117","2","9","37","Kondisi",  "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["118","2","10","38","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["119","2","10","38","Kapasitas Jamaah", "Orang",""],
        ["120","2","10","38","Kondisi", "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["121","2","10","39","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["122","2","10","39","Kapasitas Jamaah", "Orang",""],
        ["123","2","10","39","Kondisi", "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["124","2","10","40","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["125","2","10","40","Kapasitas Umat", "Orang",""],
        ["126","2","10","40","Kondisi", "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["127","2","10","41","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["128","2","10","41","Kapasitas Umat", "Orang",""],
        ["129","2","10","41","Kondisi", "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["130","2","10","42","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["131","2","10","42","Kapasitas Umat", "Orang",""],
        ["132","2","10","42","Kondisi", "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["133","2","11","43","Luas Area", "Hektar (ha)",""],
        ["134","2","11","43","Jumlah Wahana", "Unit",""],
        ["135","2","11","43","Kondisi", "Usia Wahana, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["136","2","11","44","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["137","2","11","44","Kapasitas Penonton", "Orang",""],
        ["138","2","11","44","Kondisi", "Usia Bangunan, Fasilitas Pendukung","Baik,Rusak Sedang,Rusak Parah"],
        ["139","2","11","45","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["140","2","11","45","Jenis Lapangan","Sepak bola", "basket", "tenis", "dll.",""],
        ["141","2","11","45","Kondisi", "Usia Fasilitas, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["142","2","11","46","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["143","2","11","46","Jumlah Kolam", "Unit",""],
        ["144","2","11","46","Kondisi", "Usia Fasilitas, Kebersihan Air","Baik,Rusak Sedang,Rusak Parah"],
        ["145","2","12","47","Luas Area", "Hektar (ha)",""],
        ["146","2","12","47","Jumlah Makam", "Unit",""],
        ["147","2","12","47","Kondisi", "Usia Makam, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["148","2","12","48","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["149","2","12","48","Kapasitas Pembakaran", "Unit per hari",""],
        ["150","2","12","48","Kondisi", "Usia Fasilitas, Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["151","2","12","49","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["152","2","12","49","Jumlah Makam", "Unit",""],
        ["153","2","12","49","Kondisi", "Usia Makam, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["154","2","13","50","Luas Area", "Hektar (ha)",""],
        ["155","2","13","50","Jumlah Fasilitas","Unit (misalnya", "bangku", "taman bermain)",""],
        ["156","2","13","50","Kondisi", "Usia Fasilitas, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["157","2","13","51","Luas Area", "Hektar (ha)",""],
        ["158","2","13","51","Jumlah Pohon", "Unit",""],
        ["159","2","13","51","Kondisi", "Usia Hutan, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["160","2","13","52","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["161","2","13","52","Jumlah Peralatan Bermain", "Unit",""],
        ["162","2","13","52","Kondisi", "Usia Peralatan, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["163","2","13","53","Panjang Jalur","Meter (m)",""],
        ["164","2","13","53","Lebar Jalur","Meter (m)",""],
        ["165","2","13","53","Kondisi", "Usia Jalur, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["166","2","14","54","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["167","2","14","54","Kapasitas Kendaraan", "Unit",""],
        ["168","2","14","54","Kondisi", "Usia Fasilitas, Tingkat Keamanan","Baik,Rusak Sedang,Rusak Parah"],
        ["169","2","14","55","Luas Bangunan","Meter persegi (m<sup>2</sup>)",""],
        ["170","2","14","55","Jumlah Lantai", "Unit",""],
        ["171","2","14","55","Kapasitas Kendaraan", "Unit",""],
        ["172","2","14","55","Kondisi", "Usia Fasilitas, Tingkat Keamanan","Baik,Rusak Sedang,Rusak Parah"],
        ["173","2","14","56","Panjang Area","Meter (m)",""],
        ["174","2","14","56","Kapasitas Kendaraan", "Unit",""],
        ["175","2","14","56","Kondisi", "Tingkat Keamanan, Tanda Parkir Yang Jelas","Baik,Rusak Sedang,Rusak Parah"],
        ["176","3","15","57","Kapasitas","Megawatt (MW)",""],
        ["177","3","15","57","Luas Area", "Hektar (ha)",""],
        ["178","3","15","57","Jenis Energi","Air", "batubara", "nuklir", "matahari", "angin",""],
        ["179","3","15","57","Kondisi", "Umur Fasilitas, Tingkat Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["180","3","15","58","Panjang Jaringan","Meter (m)",""],
        ["181","3","15","58","Kapasitas Transmisi", "Kilovolt (kV)",""],
        ["182","3","15","58","Kondisi", "Usia Jaringan, Frekuensi Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["183","3","15","59","Panjang Jaringan","Meter (m)",""],
        ["184","3","15","59","Kapasitas Distribusi", "Kilovolt (kV)",""],
        ["185","3","15","59","Jumlah Pengguna", "Unit rumah atau bangunan",""],
        ["186","3","15","59","Kondisi", "Usia Jaringan, Frekuensi Gangguan","Baik,Rusak Sedang,Rusak Parah"],
        ["187","3","15","60","Jumlah Meteran Terpasang","",""],
        ["188","3","15","60","Tipe Meteran", "Analog atau digital",""],
        ["189","3","15","60","Kondisi", "Kalibrasi Dan Akurasi","Baik,Rusak Sedang,Rusak Parah"],
        ["190","3","16","11","Kapasitas Produksi", "Liter per detik (L/s) atau meter kubik per hari (m<sup>2</sup>/hari)",""],
        ["191","3","16","11","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["192","3","16","11","Kondisi", "Usia Fasilitas, Tingkat Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["193","3","16","13","Panjang Jaringan","Meter (m)",""],
        ["194","3","16","13","Diameter Pipa","Milimeter (mm)",""],
        ["195","3","16","13","Kondisi", "Usia Jaringan, Tingkat Kebocoran","Baik,Rusak Sedang,Rusak Parah"],
        ["196","3","16","12","Kapasitas Penyimpanan","Meter kubik (m<sup>2</sup>)",""],
        ["197","3","16","12","Kondisi", "Usia Fasilitas, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["198","3","16","64","Jumlah Hidran","",""],
        ["199","3","16","64","Kondisi", "Fungsi Dan Aksesibilitas","Baik,Rusak Sedang,Rusak Parah"],
        ["200","3","17","65","Kapasitas Layanan", "Jumlah pelanggan yang dapat dilayani",""],
        ["201","3","17","65","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["202","3","17","65","Kondisi", "Usia Fasilitas, Teknologi Yang Digunakan","Baik,Rusak Sedang,Rusak Parah"],
        ["203","3","17","66","Panjang Jaringan","Meter (m)",""],
        ["204","3","17","66","Tipe Kabel", "Tembaga atau serat optik",""],
        ["205","3","17","66","Kondisi", "Usia Jaringan, Tingkat Gangguan","Baik,Rusak Sedang,Rusak Parah"],
        ["206","3","17","67","Jumlah BTS","",""],
        ["207","3","17","67","Kapasitas Layanan", "Jumlah pengguna yang dapat dilayani",""],
        ["208","3","17","67","Kondisi", "Usia Fasilitas, Cakupan Sinyal","Baik,Rusak Sedang,Rusak Parah"],
        ["209","3","17","68","Panjang Jaringan","Meter (m)",""],
        ["210","3","17","68","Kapasitas Data", "Gigabit per detik (Gbps)",""],
        ["211","3","17","68","Kondisi", "Usia Jaringan, Tingkat Gangguan","Baik,Rusak Sedang,Rusak Parah"],
        ["212","3","18","69","Kapasitas Produksi","Meter kubik per hari (m<sup>2</sup>/hari)",""],
        ["213","3","18","69","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["214","3","18","69","Kondisi", "Usia Fasilitas, Tingkat Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["215","3","18","70","Panjang Jaringan","Meter (m)",""],
        ["216","3","18","70","Diameter Pipa","Milimeter (mm)",""],
        ["217","3","18","70","Kondisi", "Usia Jaringan, Tingkat Kebocoran","Baik,Rusak Sedang,Rusak Parah"],
        ["218","3","18","71","Jumlah Regulator","",""],
        ["219","3","18","71","Kapasitas", "Tekanan dan aliran gas",""],
        ["220","3","18","71","Kondisi", "Fungsi Dan Keakuratan","Baik,Rusak Sedang,Rusak Parah"],
        ["221","3","18","72","Jumlah Meteran Terpasang","",""],
        ["222","3","18","72","Tipe Meteran", "Analog atau digital",""],
        ["223","3","18","72","Kondisi", "Kalibrasi Dan Akurasi","Baik,Rusak Sedang,Rusak Parah"],
        ["224","3","19","1","Panjang Jalan","Meter (m)",""],
        ["225","3","19","1","Lebar Jalan","Meter (m)",""],
        ["226","3","19","1","Kondisi",  "Kualitas Permukaan, Tingkat Kemacetan","Baik,Rusak Sedang,Rusak Parah"],
        ["227","3","19","74","Panjang Rel","Meter (m)",""],
        ["228","3","19","74","Jumlah Jalur", "Single track atau double track",""],
        ["229","3","19","74","Kondisi", "Usia Rel, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["230","3","19","75","Luas Area", "Hektar (ha)",""],
        ["231","3","19","75","Jumlah Landasan", "Unit",""],
        ["232","3","19","75","Kondisi", "Usia Fasilitas, Tingkat Kemacetan","Baik,Rusak Sedang,Rusak Parah"],
        ["233","3","19","76","Luas Area", "Hektar (ha)",""],
        ["234","3","19","76","Kapasitas Kapal", "Jumlah kapal yang dapat ditampung",""],
        ["235","3","19","76","Kondisi", "Usia Fasilitas, Tingkat Efisiensi","Baik,Rusak Sedang,Rusak Parah"],
        ["236","3","19","77","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["237","3","19","77","Kapasitas Penumpang", "Jumlah penumpang per hari",""],
        ["238","3","19","77","Kondisi", "Usia Fasilitas, Tingkat Kenyamanan","Baik,Rusak Sedang,Rusak Parah"],
        ["239","3","19","78","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["240","3","19","78","Kapasitas Penumpang", "Jumlah penumpang per hari",""],
        ["241","3","19","78","Kondisi", "Usia Fasilitas, Tingkat Kenyamanan","Baik,Rusak Sedang,Rusak Parah"],
        ["242","3","20","79","Jumlah Stasiun","",""],
        ["243","3","20","79","Luas Area","Meter persegi (m<sup>2</sup>)",""],
        ["244","3","20","79","Kondisi", "Usia Fasilitas, Tingkat Kesiapan","Baik,Rusak Sedang,Rusak Parah"],
        ["245","3","20","80","Jumlah Kendaraan","",""],
        ["246","3","20","80","Kapasitas Tangki Air", "Liter (L)",""],
        ["247","3","20","80","Kondisi", "Usia Kendaraan, Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["248","3","20","81","Jumlah Hidran","",""],
        ["249","3","20","81","Kapasitas Aliran Air", "Liter per detik (L/s)",""],
        ["250","3","20","81","Kondisi", "Fungsi Dan Aksesibilitas","Baik,Rusak Sedang,Rusak Parah"],
        ["251","3","20","82","Jumlah APAR","",""],
        ["252","3","20","82","Jenis APAR","Air,CO2,bubuk kimia","Air,CO2,bubuk kimia"],
        ["253","3","20","82","Kondisi", "Fungsi Dan Tingkat Pemeliharaan","Baik,Rusak Sedang,Rusak Parah"],
        ["254","3","21","6","Jumlah Lampu","",""],
        ["255","3","21","6","Jenis Lampu","LED, sodium, merkuri","LED, sodium, merkuri"],
        ["256","3","21","6","Kondisi",  "Fungsi Dan Efisiensi Energi","Baik,Rusak Sedang,Rusak Parah"],
        ["257","3","21","84","Jumlah Tiang","",""],
        ["258","3","21","84","Tinggi Tiang","Meter (m)",""],
        ["259","3","21","84","Kondisi", "Struktur Dan Stabilitas","Baik,Rusak Sedang,Rusak Parah"],
        ["260","3","21","85","Panjang Jaringan","Meter (m)",""],
        ["261","3","21","85","Tipe Kabel", "Bawah tanah atau udara",""],
        ["262","3","21","85","Kondisi", "Usia Jaringan, Tingkat Gangguan","Baik,Rusak Sedang,Rusak Parah"],
        ["263","3","21","86","Jumlah Sistem Terpasang","",""],
        ["264","3","21","86","Tipe Sistem","Timer", "sensor cahaya",""],
        ["265","3","21","86","Kondisi", "Fungsi dan keakuratan","Baik,Rusak Sedang,Rusak Parah"]
        ];
        
        foreach($dt_psu_attributes as $i => $pattr)
        {
            PsuAttributeModel::firstOrCreate(
                    ['id' => $pattr[0]],
                    [
                        'id_kategori' => $pattr[1],
                        'id_jenis_psu' => $pattr[2],
                        'id_psu' => $pattr[3],
                        'attribute' => $pattr[4],
                        'keterangan' => $pattr[5],
                        'options' => $pattr[6],
                    ]);
        }
    }
}
